### ISSUE TITLE
Problems getting localtunnel client work with localtunnel server

### ISSUE THREAD

**Issue by a-stankevich** [angelobreuer/localtunnel.net#16]
Dear @angelobreuer, thanks for you great work with these tools.

I'm trying to run them together and looks like something doesn't quite connect.

The server is running at localtunnel.net as docker image like this:
`docker run -it --env Dns__Zone=localtunnel.net --network host angelobreuer/localtunnel-server`

The client is started as 
`localtunnel --subdomain test01 -s http://localtunnel.net --port 8149 -v http`

The client is able to obtain subdomain and port, the port is available. 
But once HTTP request is actually sent, the server crashes with error 500:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://test01.localtunnel.net/ - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMJEU290K6JJ", Request id "0HMJEU290K6JJ:00000002": An unhandled exception was thrown by the application.
      System.Net.Http.HttpRequestException: An error occurred while sending the request.
       ---> System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer.
       ---> System.Net.Sockets.SocketException (104): Connection reset by peer
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
         at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
         at Localtunnel.Server.IO.DelegatingCloseStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken) in /src/src/Localtunnel.Server/IO/DelegatingCloseStream.cs:line 169
         at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
         at System.Net.Http.HttpConnection.FlushAsync(Boolean async)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
         at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
         at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
         at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
         at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
         at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
         at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
         at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
         at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
         at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
         at System.Threading.ThreadPoolWorkQueue.Dispatch()
         at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
         at System.Threading.Thread.StartCallback()
      --- End of stack trace from previous location ---

         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendRequestContentAsync(HttpRequestMessage request, HttpContentWriteStream stream, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Localtunnel.Server.TunnelInformation.HandleHttpConnection(HttpRequest httpRequest, HttpResponse httpResponse, CancellationToken cancellationToken) in /src/src/Localtunnel.Server/TunnelInformation.cs:line 114
         at Localtunnel.Server.TunnelRequestHandler.HandleEndpointAsync(HttpContext httpContext, TunnelId tunnelId) in /src/src/Localtunnel.Server/Http/TunnelRequestHandler.cs:line 89
         at Localtunnel.Server.TunnelRequestHandler.HandleRequestInternalAsync(HttpContext httpContext) in /src/src/Localtunnel.Server/Http/TunnelRequestHandler.cs:line 79
         at Localtunnel.Server.TunnelRequestHandler.HandleRequestAsync(HttpContext httpContext, Func`1 next) in /src/src/Localtunnel.Server/Http/TunnelRequestHandler.cs:line 52
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://test01.localtunnel.net/ - - - 500 0 - 18.7578ms
```

Some more screenshots in case they may help

The client is connected:
![image](https://user-images.githubusercontent.com/6768522/180986818-f85a11fa-12a2-461d-8fe2-4aac1fe5b8d7.png)

The port is available on server:
![image](https://user-images.githubusercontent.com/6768522/180986955-fcf565f3-ac8a-4bf6-a2dc-3c66ab463d26.png)

Error 500 returned:
![image](https://user-images.githubusercontent.com/6768522/180987029-3f59a611-5b4d-4b52-a11a-b50e6337c614.png)

Could you please advise, what else should I check to make this work?

**Comment by angelobreuer** [comment]
Is the destination server up the localtunnel client wants to reach? It seems like the request is aborted after it is send

Could you try to run the client with the --no-dashboard option? Else the logs are cluttered by the dashboard

**Comment by a-stankevich** [comment]
Yes, the server is up. Direct curl works:

![image](https://user-images.githubusercontent.com/6768522/181214533-7eebbf86-c35c-41ef-82a8-7aacfcbbf5f8.png)

In the localtunnel client output I see no indication of any attempts:

![image](https://user-images.githubusercontent.com/6768522/181214754-1da553e1-7b8b-4cc8-869f-9006652a5de9.png)

Also if I start the node.js localtunnel server and client instead of .net versions, it works.

The server at `localtunnel.net` is up and running if you would like to try to connect to it.
I can also give you access to it if you'd like to debug or view logs.

**Comment by a-stankevich** [comment]
I just noticed that removing -d test01 actually works better and does generate some connections on localtunnel client.

The server still returns error 500, but this time it's different

![image](https://user-images.githubusercontent.com/6768522/181216772-df76fb73-3401-45d4-adf3-8f7cb6320cc7.png)

I'll continue trying different options and will keep you posted

**Comment by angelobreuer** [comment]
I think you are using an older docker build than my machine. I pushed a new one as docker.io/angelobreuer/localtunnel-server, could you try that?

**Comment by angelobreuer** [comment]
It seems like the first request gets through but then all subsequent requests fail. I have tried your server and it seems that only the first is send, and then the server will respond with a 500 Internal Server Error if you try to send further requests on the same subdomain

**Comment by a-stankevich** [comment]
I've updated the docker image and it works much better now, thank you.

The problem with 500 error is still there though, but looks like it's caused by HttpClient on the server following redirects instead of passing them back, even when the client is in pass-throught mode.

Here's an example:
![image](https://user-images.githubusercontent.com/6768522/181231323-f464f28e-4769-4a2b-8398-866bf9faeb4c.png)

The server responded with redirect 302 to "/", which should have been read by browser, making the URL in browser update and resulting in another request. But instead it seems like this was handled by HttpClient on the server, which followed the redirect and retreived the content with status code 200. The problem with that behavior is that the browser doesn't know the new URL and keeps requesting all other content relative to the original URL.

When "/" is requested without authorization my app also returns 302 and looks like that's where the server crashes with 500 error, as something doesn't quite work in that redirect following. My guess is that using `AllowAutoRedirect = false` on HttpClientHandler should resolve both issues.

Another strange thing I noticed is that requests for some resources return `304 Not Modified` even though requested without "If-Modified-Since" header. 
![image](https://user-images.githubusercontent.com/6768522/181232020-931fdf92-f660-4ab7-b097-17ad44770150.png)

This can probably be related to some caching implemented in the HttpClient. Let me know if you'd like me to create a new issue on this.

Thank you

**Comment by angelobreuer** [comment]
Thank you, the issue with automatic redirect following on the server-side should be fixed by 2https://github.com/angelobreuer/localtunnel.net/commit/4a989f60446fa90f63d2eeba95790d3e9941988d. I published a new docker image

**Comment by angelobreuer** [comment]
Closing due to stale, please reopen the issue, if the problem still persists

**Comment by a-stankevich** [comment]
This works as expected with the new version, thank you for fixing!
